[general]
static=yes
writeprotect=yes
clearglobalvars=yes

[globals]

[rr-phone-check]
exten => s,1,Set(CDR_PROP(disable)=1)
 same => n,Set(TIMEOUT(absolute)=20)
 same => n,Playback(hello)
 same => n,Playback(your)
 same => n,Playback(extension)
 same => n,Playback(is)
 same => n,SayDigits(${RINGRING_EXTENSION})
 same => n,Playback(auth-thankyou)
 same => n,Hangup()

#include /var/lib/ringring/asterisk/extensions.conf
