[modules]
autoload=yes
noload => chan_alsa.so
noload => chan_console.so
noload => chan_mobile.so
noload => chan_ooh323.so
noload => chan_phone.so
noload => chan_skinny.so
noload => res_http_websocket.so
