package telephony

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	extensionrules "github.com/amcchord/ringring/internal/extension"
	"github.com/amcchord/ringring/internal/model"
	"github.com/amcchord/ringring/internal/radio"
)

var (
	safeIdentifier = regexp.MustCompile(`^[A-Za-z0-9_-]{1,48}$`)
)

type DialDevice struct {
	PartyID     string
	Extension   string
	DeviceID    string
	SIPUsername string
	SIPSecret   string
}

type Configuration struct {
	PJSIP    []byte
	Dialplan []byte
}

func Render(devices []DialDevice, services []model.RoutingServices) (Configuration, error) {
	ordered := append([]DialDevice(nil), devices...)
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].PartyID != ordered[j].PartyID {
			return ordered[i].PartyID < ordered[j].PartyID
		}
		if ordered[i].Extension != ordered[j].Extension {
			return ordered[i].Extension < ordered[j].Extension
		}
		return ordered[i].SIPUsername < ordered[j].SIPUsername
	})

	var pjsip, dialplan bytes.Buffer
	pjsip.WriteString("; Generated by RingRing. Manual changes will be overwritten.\n\n")
	dialplan.WriteString("; Generated by RingRing. Manual changes will be overwritten.\n\n")

	parties := make(map[string]map[string][]string)
	partyIDs := make(map[string]string)
	deviceIDs := make(map[string]struct{}, len(ordered))
	sipUsernames := make(map[string]struct{}, len(ordered))
	for _, device := range ordered {
		if err := validateDevice(device); err != nil {
			return Configuration{}, err
		}
		if _, exists := deviceIDs[device.DeviceID]; exists {
			return Configuration{}, errors.New("duplicate device ID in routing configuration")
		}
		deviceIDs[device.DeviceID] = struct{}{}
		if _, exists := sipUsernames[device.SIPUsername]; exists {
			return Configuration{}, errors.New("duplicate SIP username in routing configuration")
		}
		sipUsernames[device.SIPUsername] = struct{}{}
		contextName := partyContext(device.PartyID)
		if parties[contextName] == nil {
			parties[contextName] = make(map[string][]string)
			partyIDs[contextName] = device.PartyID
		}
		parties[contextName][device.Extension] = append(parties[contextName][device.Extension], device.SIPUsername)

		fmt.Fprintf(&pjsip, "[%s-auth]\n", device.SIPUsername)
		pjsip.WriteString("type=auth\nauth_type=userpass\n")
		fmt.Fprintf(&pjsip, "username=%s\npassword=%s\n\n", device.SIPUsername, device.SIPSecret)

		// Asterisk's registrar resolves the REGISTER To user directly to an
		// AOR object name, so the AOR must match the phone's SIP username.
		fmt.Fprintf(&pjsip, "[%s]\n", device.SIPUsername)
		pjsip.WriteString("type=aor\nmax_contacts=1\nremove_existing=yes\nqualify_frequency=60\n\n")

		fmt.Fprintf(&pjsip, "[%s]\n", device.SIPUsername)
		pjsip.WriteString("type=endpoint\ndisallow=all\nallow=ulaw,alaw,g722\ndirect_media=no\n")
		pjsip.WriteString("rtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n")
		fmt.Fprintf(&pjsip, "context=%s\nauth=%s-auth\naors=%s\ncallerid=RingRing %s <%s>\n\n",
			contextName, device.SIPUsername, device.SIPUsername, device.Extension, device.Extension)
	}
	serviceByParty := make(map[string]model.RoutingServices, len(services))
	for _, service := range services {
		if !safeIdentifier.MatchString(service.PartyID) {
			return Configuration{}, errors.New("service party ID contains unsupported characters")
		}
		if _, exists := serviceByParty[service.PartyID]; exists {
			return Configuration{}, errors.New("duplicate party service configuration")
		}
		serviceByParty[service.PartyID] = service
	}

	contexts := make([]string, 0, len(parties))
	for contextName := range parties {
		contexts = append(contexts, contextName)
	}
	sort.Strings(contexts)
	for _, contextName := range contexts {
		fmt.Fprintf(&dialplan, "[%s]\n", contextName)
		dialplan.WriteString("exten => *10,1,Answer()\n")
		dialplan.WriteString(" same => n,Wait(1)\n")
		dialplan.WriteString(" same => n,Playback(beep)\n")
		dialplan.WriteString(" same => n,Echo()\n")
		dialplan.WriteString(" same => n,Playback(demo-echodone)\n")
		dialplan.WriteString(" same => n,Hangup()\n")
		dialplan.WriteString("exten => *15,1,Answer()\n")
		dialplan.WriteString(" same => n,Wait(1)\n")
		dialplan.WriteString(" same => n,Set(AGIEXITONHANGUP=yes)\n")
		fmt.Fprintf(&dialplan, " same => n,AGI(agi://app:4573/choose-extension,%s,${CHANNEL(endpoint)})\n", partyIDs[contextName])
		writeAGIFailureFallback(&dialplan)
		service := serviceByParty[partyIDs[contextName]]
		if service.TimeEnabled {
			dialplan.WriteString("exten => *11,1,Answer()\n")
			dialplan.WriteString(" same => n,Wait(1)\n")
			dialplan.WriteString(" same => n,SayUnix(${EPOCH},,ABdY 'digits/at' IMp)\n")
			dialplan.WriteString(" same => n,Hangup()\n")
		}
		if service.WeatherEnabled {
			dialplan.WriteString("exten => *12,1,Answer()\n")
			dialplan.WriteString(" same => n,Wait(1)\n")
			fmt.Fprintf(&dialplan, " same => n,AGI(agi://app:4573/weather,%s)\n", service.PartyID)
			writeAGIFailureFallback(&dialplan)
		}
		if service.RadioEnabled {
			station, ok := radio.Resolve(service.RadioStation)
			if !ok {
				return Configuration{}, errors.New("radio station is not in the catalog")
			}
			dialplan.WriteString("exten => *13,1,Answer()\n")
			dialplan.WriteString(" same => n,Wait(1)\n")
			fmt.Fprintf(&dialplan, " same => n,MP3Player(%s)\n", station.StreamURL)
			writeFriendlyServiceUnavailable(&dialplan)
			dialplan.WriteString(" same => n,Hangup()\n")
		}
		if service.AIEnabled {
			dialplan.WriteString("exten => *14,1,Answer()\n")
			dialplan.WriteString(" same => n,Set(RINGRING_AI_CALL_ID=${UUID()})\n")
			dialplan.WriteString(" same => n,Set(RINGRING_AI_READY=0)\n")
			dialplan.WriteString(" same => n,Set(RINGRING_AI_DENIED=0)\n")
			fmt.Fprintf(&dialplan, " same => n,AGI(agi://app:4573/ai-authorize,%s,${RINGRING_AI_CALL_ID},${CHANNEL(endpoint)})\n", service.PartyID)
			dialplan.WriteString(" same => n,GotoIf($[\"${RINGRING_AI_READY}\"=\"1\"]?bridge:unavailable)\n")
			dialplan.WriteString(" same => n(unavailable),GotoIf($[\"${RINGRING_AI_DENIED}\"=\"1\"]?done:retry)\n")
			dialplan.WriteString(" same => n(bridge),Dial(AudioSocket/app:4574/${RINGRING_AI_CALL_ID}/c(slin))\n")
			dialplan.WriteString(" same => n,Hangup()\n")
			dialplan.WriteString(" same => n(retry),Playback(sorry)\n")
			dialplan.WriteString(" same => n,Playback(please-try-call-later)\n")
			dialplan.WriteString(" same => n(done),Hangup()\n")
		}

		extensions := make([]string, 0, len(parties[contextName]))
		for extension := range parties[contextName] {
			extensions = append(extensions, extension)
		}
		sort.Strings(extensions)
		for _, extension := range extensions {
			endpoints := parties[contextName][extension]
			for i := range endpoints {
				endpoints[i] = "PJSIP/" + endpoints[i]
			}
			fmt.Fprintf(&dialplan, "exten => %s,1,NoOp(RingRing party call)\n", extension)
			fmt.Fprintf(&dialplan, " same => n,Dial(%s,30)\n", strings.Join(endpoints, "&"))
			dialplan.WriteString(" same => n,GotoIf($[\"${DIALSTATUS}\"=\"ANSWER\"]?done:unavailable)\n")
			dialplan.WriteString(" same => n(unavailable),Answer()\n")
			dialplan.WriteString(" same => n,Wait(1)\n")
			writeFriendlyPhoneUnavailable(&dialplan)
			dialplan.WriteString(" same => n(done),Hangup()\n")
		}
		writeFriendlyInvalid(&dialplan, "_X!")
		writeFriendlyInvalid(&dialplan, "_*X!")
		dialplan.WriteString("\n")
	}

	return Configuration{PJSIP: pjsip.Bytes(), Dialplan: dialplan.Bytes()}, nil
}

func writeAGIFailureFallback(dialplan *bytes.Buffer) {
	dialplan.WriteString(" same => n,GotoIf($[\"${AGISTATUS}\"=\"SUCCESS\"]?done:unavailable)\n")
	dialplan.WriteString(" same => n(unavailable),Playback(sorry)\n")
	dialplan.WriteString(" same => n,Playback(please-try-call-later)\n")
	dialplan.WriteString(" same => n(done),Hangup()\n")
}

func writeFriendlyServiceUnavailable(dialplan *bytes.Buffer) {
	dialplan.WriteString(" same => n,Playback(sorry)\n")
	dialplan.WriteString(" same => n,Playback(please-try-call-later)\n")
}

func writeFriendlyPhoneUnavailable(dialplan *bytes.Buffer) {
	dialplan.WriteString(" same => n,Playback(sorry)\n")
	dialplan.WriteString(" same => n,Playback(number-not-answering)\n")
	dialplan.WriteString(" same => n,Playback(please-try-call-later)\n")
}

func writeFriendlyInvalid(dialplan *bytes.Buffer, pattern string) {
	fmt.Fprintf(dialplan, "exten => %s,1,Answer()\n", pattern)
	dialplan.WriteString(" same => n,Wait(1)\n")
	dialplan.WriteString(" same => n,Playback(sorry)\n")
	dialplan.WriteString(" same => n,Playback(cannot-complete-as-dialed)\n")
	dialplan.WriteString(" same => n,Playback(please-try-again)\n")
	dialplan.WriteString(" same => n,Hangup()\n")
}

func FromRoutingDevices(devices []model.RoutingDevice, decrypt func(string, []byte) (string, error)) ([]DialDevice, error) {
	result := make([]DialDevice, 0, len(devices))
	for _, device := range devices {
		secret, err := decrypt(device.SIPSecretCiphertext, []byte(device.DeviceID))
		if err != nil {
			return nil, fmt.Errorf("decrypt SIP credential for device %s: %w", device.DeviceID, err)
		}
		result = append(result, DialDevice{
			PartyID: device.PartyID, Extension: device.Extension, DeviceID: device.DeviceID,
			SIPUsername: device.SIPUsername, SIPSecret: secret,
		})
	}
	return result, nil
}

func validateDevice(device DialDevice) error {
	if !safeIdentifier.MatchString(device.PartyID) {
		return errors.New("party ID contains unsupported characters")
	}
	if !safeIdentifier.MatchString(device.DeviceID) {
		return errors.New("device ID contains unsupported characters")
	}
	if !safeIdentifier.MatchString(device.SIPUsername) {
		return errors.New("SIP username contains unsupported characters")
	}
	if !extensionrules.Valid(device.Extension) {
		return errors.New("extension is malformed or reserved for public safety")
	}
	if strings.ContainsAny(device.SIPSecret, "\r\n") || device.SIPSecret == "" {
		return errors.New("SIP secret contains unsupported characters")
	}
	return nil
}

func partyContext(partyID string) string {
	// Party IDs have already been restricted to Asterisk-safe characters and
	// 48 bytes. Preserve every byte: normalization or truncation could map two
	// tenants into one dialplan context and break the core call boundary.
	return "rr-party-" + partyID
}
