package telephony

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/amcchord/ringring/internal/model"
)

var (
	safeIdentifier = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)
	safeExtension  = regexp.MustCompile(`^[0-9]{2,5}$`)
)

type DialDevice struct {
	PartyID     string
	Extension   string
	DeviceID    string
	SIPUsername string
	SIPSecret   string
}

type Configuration struct {
	PJSIP    []byte
	Dialplan []byte
}

func Render(devices []DialDevice) (Configuration, error) {
	ordered := append([]DialDevice(nil), devices...)
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].PartyID != ordered[j].PartyID {
			return ordered[i].PartyID < ordered[j].PartyID
		}
		if ordered[i].Extension != ordered[j].Extension {
			return ordered[i].Extension < ordered[j].Extension
		}
		return ordered[i].SIPUsername < ordered[j].SIPUsername
	})

	var pjsip, dialplan bytes.Buffer
	pjsip.WriteString("; Generated by RingRing. Manual changes will be overwritten.\n\n")
	dialplan.WriteString("; Generated by RingRing. Manual changes will be overwritten.\n\n")

	parties := make(map[string]map[string][]string)
	for _, device := range ordered {
		if err := validateDevice(device); err != nil {
			return Configuration{}, err
		}
		contextName := partyContext(device.PartyID)
		if parties[contextName] == nil {
			parties[contextName] = make(map[string][]string)
		}
		parties[contextName][device.Extension] = append(parties[contextName][device.Extension], device.SIPUsername)

		fmt.Fprintf(&pjsip, "[%s-auth]\n", device.SIPUsername)
		pjsip.WriteString("type=auth\nauth_type=userpass\n")
		fmt.Fprintf(&pjsip, "username=%s\npassword=%s\n\n", device.SIPUsername, device.SIPSecret)

		fmt.Fprintf(&pjsip, "[%s-aor]\n", device.SIPUsername)
		pjsip.WriteString("type=aor\nmax_contacts=1\nremove_existing=yes\nqualify_frequency=60\n\n")

		fmt.Fprintf(&pjsip, "[%s]\n", device.SIPUsername)
		pjsip.WriteString("type=endpoint\ndisallow=all\nallow=ulaw,alaw,g722\ndirect_media=no\n")
		pjsip.WriteString("rtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n")
		fmt.Fprintf(&pjsip, "context=%s\nauth=%s-auth\naors=%s-aor\ncallerid=RingRing %s <%s>\n\n",
			contextName, device.SIPUsername, device.SIPUsername, device.Extension, device.Extension)
	}

	contexts := make([]string, 0, len(parties))
	for contextName := range parties {
		contexts = append(contexts, contextName)
	}
	sort.Strings(contexts)
	for _, contextName := range contexts {
		fmt.Fprintf(&dialplan, "[%s]\n", contextName)
		dialplan.WriteString("exten => *11,1,Answer()\n")
		dialplan.WriteString(" same => n,Wait(1)\n")
		dialplan.WriteString(" same => n,SayUnix(${EPOCH},,ABdY 'digits/at' IMp)\n")
		dialplan.WriteString(" same => n,Hangup()\n")

		extensions := make([]string, 0, len(parties[contextName]))
		for extension := range parties[contextName] {
			extensions = append(extensions, extension)
		}
		sort.Strings(extensions)
		for _, extension := range extensions {
			endpoints := parties[contextName][extension]
			for i := range endpoints {
				endpoints[i] = "PJSIP/" + endpoints[i]
			}
			fmt.Fprintf(&dialplan, "exten => %s,1,NoOp(RingRing party call)\n", extension)
			fmt.Fprintf(&dialplan, " same => n,Dial(%s,30)\n", strings.Join(endpoints, "&"))
			dialplan.WriteString(" same => n,Hangup()\n")
		}
		dialplan.WriteString("exten => _X!,1,Playback(invalid)\n same => n,Hangup()\n\n")
	}

	return Configuration{PJSIP: pjsip.Bytes(), Dialplan: dialplan.Bytes()}, nil
}

func FromRoutingDevices(devices []model.RoutingDevice, decrypt func(string, []byte) (string, error)) ([]DialDevice, error) {
	result := make([]DialDevice, 0, len(devices))
	for _, device := range devices {
		secret, err := decrypt(device.SIPSecretCiphertext, []byte(device.DeviceID))
		if err != nil {
			return nil, fmt.Errorf("decrypt SIP credential for device %s: %w", device.DeviceID, err)
		}
		result = append(result, DialDevice{
			PartyID: device.PartyID, Extension: device.Extension, DeviceID: device.DeviceID,
			SIPUsername: device.SIPUsername, SIPSecret: secret,
		})
	}
	return result, nil
}

func validateDevice(device DialDevice) error {
	if !safeIdentifier.MatchString(device.PartyID) {
		return errors.New("party ID contains unsupported characters")
	}
	if !safeIdentifier.MatchString(device.DeviceID) {
		return errors.New("device ID contains unsupported characters")
	}
	if !safeIdentifier.MatchString(device.SIPUsername) {
		return errors.New("SIP username contains unsupported characters")
	}
	if !safeExtension.MatchString(device.Extension) {
		return errors.New("extension must contain 2 to 5 digits")
	}
	if strings.ContainsAny(device.SIPSecret, "\r\n") || device.SIPSecret == "" {
		return errors.New("SIP secret contains unsupported characters")
	}
	return nil
}

func partyContext(partyID string) string {
	compact := strings.ReplaceAll(partyID, "_", "-")
	if len(compact) > 28 {
		compact = compact[:28]
	}
	return "rr-party-" + compact
}
